### ISSUE TITLE
Have `bencher run` comment on PRs

### ISSUE THREAD

**Issue by epompeii** [bencherdev/bencher#160]
It would be nice to see the status of a run in the PR itself as opposed to having to dig into the action logs.

**Comment by untitaker** [comment]
codecov has this, but i find it really noisy because it comments even if there is nothing wrong. I would like bencher to comment or publish a "failing CI status" if there is an actual performance regression by some threshold, i.e. "post comment if there's more than a 5% slowdown compared to master"

even cooler would be an alerting system that allows you to configure custom rules like that.

**Comment by epompeii** [comment]
Possible inspiration: https://github.com/rust-lang/rustc-perf/issues/1214

**Comment by epompeii** [comment]
Alternative option is to just comment as a part of the GitHub Action: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Comment by epompeii** [comment]
Completed in: https://github.com/bencherdev/bencher/releases/tag/v0.3.6
