### ISSUE TITLE
https://bencher.dev/ theme doesn't change when system color scheme changes

### ISSUE THREAD

**Issue by hamirmahal** [bencherdev/bencher#399]

**Comment by hamirmahal** [comment]
[Screencast from 05-26-2024 02:06:25 PM.webm](https://github.com/bencherdev/bencher/assets/43425812/f51548da-4593-4ad1-877b-57ddd9278a4c)

**Comment by epompeii** [comment]
Thank you for pointing this out and for the PR!

I have opted to refactor the code similar to how you suggested. However, I wanted to reuse the same logic for reading from the local storage in both places in the code. This is the commit: https://github.com/bencherdev/bencher/commit/00fc5a044dc6ad4f73444451caa3792edbfd4a6a

I'll leave this issue open until the fix gets deployed as a part of the next release.

**Comment by epompeii** [comment]
Completed: https://github.com/bencherdev/bencher/releases/tag/v0.4.11

**Comment by epompeii** [comment]
It isn't worth reopening this issue, but I just wanted to note that there was a bug in the initial fix for this issue.

When using the system default for the theme, the navbar wordmark and a few other things weren't being updated properly. This can be seen in the example video for the PR: https://github.com/bencherdev/bencher/pull/400#issuecomment-2132396198

This has been fixed in this commit: https://github.com/bencherdev/bencher/commit/d103b84f8c6872920b2c5743c0f8097462a58ac4
