### ISSUE TITLE
Hyperfine adapter : Mean / median of results that have the same command name

### ISSUE THREAD

**Issue by ricardaxel** [bencherdev/bencher#471]
Hello,

Say I have the following hyperfine result.json file (notice that the command name is the same for both results)

```
{
  "results": [
     {
       "command": "my_prog",
       "mean": 1,
       ...
     },
     {
       "command": "my_prog",
       "mean": 2,
       ...
     }
  ]
}
```

For now, from what I can read from `src/adapters/shell/hyperfine.rs`, this will create 2 entries in benchmark_metrics vector. 
Would it be possible to have instead a single entry that is the mean/median of the two ?  
(So that `benchmark_metrics = [JsonMetric { value: 1.5, ... }]` in this case)

the use case would be to benchmark a pseudo-random program that takes a seed as input : the interesting Metric is the mean / median time of N execution with N different seed.

Using hyperfine adapter, I can do the following :

```
>> hyperfine --command-name my_prog --export-json result.json --parameter-scan seed 1 10 './my_prog {seed}'
```

But then I can't aggregate these 10 results into a single one with bencher.

**Comment by epompeii** [comment]
> For now, from what I can read from `src/adapters/shell/hyperfine.rs`, this will create 2 entries in benchmark_metrics vector.

I don't believe so. I'm pretty sure that your example will insert twice into [the `ResultsMap`](https://github.com/bencherdev/bencher/blob/main/lib%2Fbencher_adapter%2Fsrc%2Fresults%2Fadapter_results.rs#L21).

The first insert will use the key `my_prog` with a Metric value of `1`. The second insert will also use the key `my_prog` with a Metric value of `2`. That is, the second insert will overwrite the first insert in the `ResultsMap`.*

In order to have two elements in [the `ResultsArray`]( https://github.com/bencherdev/bencher/blob/aa31a002842cfb0da9d6c60569396fc5261f5111/lib/bencher_adapter/src/results/mod.rs#L22), you will need to use [the `--iter` option](https://bencher.dev/docs/explanation/bencher-run/#--iter-iter) for `bencher run`.
You can then use [the `--fold` option](https://bencher.dev/docs/explanation/bencher-run/#--fold-fold) for `bencher run` to get the mean or median of the results.

Unfortunately, this won't work as intended with [`hyperfine` parameterized benchmarks](https://github.com/sharkdp/hyperfine#parameterized-benchmarks), since `hyperfine` is operating as an inner loop of sorts and `bencher run` is operating as an outer loop.

If you want to use the `hyperfine` parameterization, then you will need to handle parsing the `hyperfine` JSON output and doing the mean and median calculations yourself. Then you can output your results as [Bencher Metric Format (BMF) JSON](https://bencher.dev/docs/reference/bencher-metric-format/) and use [the JSON adapter](https://bencher.dev/docs/explanation/adapters/#-json).

---

* I see this as a bug. Bencher should treat parameterized results as different benchmarks.

**Comment by ricardaxel** [comment]
Ok I'll do it on my side then.

Just to be clear, this is not hyperfine parameterized benchmarks that give the same name :

``` bash
>> hyperfine --export-json hyper.json -P time 0 2 'sleep {time}'
>> grep "command" hyper.json 
      "command": "sleep 0",
      "command": "sleep 1",
      "command": "sleep 2",
```

It is the `--command-name` option that does that : 
``` bash
>> hyperfine --command-name FOO --export-json hyper.json -P time 0 2 'sleep {time}'
>> grep "command" hyper.json 
      "command": "FOO",
      "command": "FOO",
      "command": "FOO",

```
