### ISSUE TITLE
bencher up fails: manifest unknown

### ISSUE THREAD

**Issue by mwasplund** [bencherdev/bencher#510]
Running bencher up on windows with docker desktop fails with an invalid version tag. It looks like it is trying to use 0.4.20 when it should be v0.4.20.

```
PowerShell 7.4.5
PS C:\Users\masplund> bencher up
Pulling `ghcr.io/bencherdev/bencher-console:0.4.20` image...

Failed to pull Docker image (`ghcr.io/bencherdev/bencher-console:0.4.20`): Docker responded with status code 500: manifest unknown
```

**Comment by mwasplund** [comment]
Also Grafana uses port 3000 by default. Please pick a different port :)

**Comment by mwasplund** [comment]
PS C:\Users\masplund> bencher up --tag v0.4.20
Pulling `ghcr.io/bencherdev/bencher-console:v0.4.20` image...
Pulling `ghcr.io/bencherdev/bencher-api:v0.4.20` image...
Creating `bencher_api` container...
Starting `bencher_api` container...

Creating `bencher_console` container...
Starting `bencher_console` container...

**Comment by epompeii** [comment]
@mwasplund thank you checking out Bencher, and I'm sorry you're running into trouble.

> It looks like it is trying to use 0.4.20 when it should be v0.4.20.

Thanks for narrowing this down for me. I'll get a fix out in this upcoming release. I'm also open to a PR to fix this if you want to give it a go 😃

> Also Grafana uses port 3000 by default. Please pick a different port :)

Yes, so do a lot of frontend development servers. It's a bit of a de facto standard which is why I chose it.
I'll make sure to add some docs around how to change the port number here: https://github.com/bencherdev/bencher/issues/493

**Comment by epompeii** [comment]
@mwasplund thank you again for the bug report!

Completed: https://bencher.dev/docs/reference/changelog/#v0421

**Comment by epompeii** [comment]
> Also Grafana uses port 3000 by default. Please pick a different port :)

@mwasplund I also added `--api-port` and `--console-port` options to `bencher up` to customize the external API and Console UI ports. So you can now use a port other than `3000`. Just make sure to set the `console.url` in the API server config: https://bencher.dev/docs/reference/server-config/#console
